# Build Darkly and publish release
name: Darkly AUR build
on: workflow_dispatch
env:
  PACKAGE_UTILS_REPO: darkly-packager
  PACKAGE_UTILS_REPO_OWNER: deltacopy
  MAKEPKG_CONF: $GITHUB_WORKSPACE/.github/assets/makepkg.conf
  PACKAGER_UTILS_PATH: $GITHUB_WORKSPACE/packager-utils
jobs:
  build:
    runs-on: ubuntu-24.04
    container: archlinux:latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v4.2.0
        with:
          sparse-checkout: .github/assets/makepkg.conf
      - name: Checkout packager utils repository
        uses: actions/checkout@v4.2.0
        with:
          repository: ${{ env.PACKAGE_UTILS_REPO_OWNER }}/${{ env.PACKAGE_UTILS_REPO }}
          path: packager-utils
      - name: Overwrite /etc/makepkg.conf
        run: |
          cp ${{ env.MAKEPKG_CONF }} /etc/makepkg.conf
      - name: System update
        run: pacman -Syu --noconfirm
      - name: Install sudo, git and compile dependencies
        run: |
          pacman -Sy sudo git binutils make gcc pkg-config fakeroot plasma-desktop \
          cmake extra-cmake-modules qt6-base \
          kdecoration qt6-declarative kcoreaddons \
          kcmutils kcolorscheme kconfig kguiaddons \
          kiconthemes kwindowsystem kcmutils5 \
          frameworkintegration5 kconfigwidgets5 kiconthemes5 \
          kirigami2 kwindowsystem5 --noconfirm
      - name: Setup build user
        run: |
          useradd builduser -m # Create the builduser
          passwd -d builduser # Delete the buildusers password
          printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo
      - name: Update package files
        run: |
          chown -R builduser ${{ env.PACKAGER_UTILS_PATH }}
          sudo -u builduser bash -c 'cd packager-utils; python packager.py --dist arch'
      - name: Build package
        run: |
          cat ${{ env.PACKAGER_UTILS_PATH }}/output/AUR/darkly/PKGBUILD
          sudo -u builduser bash -c 'cd packager-utils/output/AUR/darkly; makepkg -s'
